spring:
  application:
    name: cards-service
  datasource:
    url: jdbc:h2:mem:accountsdb
    username: sa
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    info:
      env:
        enabled: true
    health:
      readinessState:
        enabled: true
      livenessState:
        enabled: true
      probes:
        enabled: true

server:
  port: 9000

build:
  version: 3.0.0
cards:
  message: "Welcome to DemoBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@demobank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/

info:
  app:
    description: "Cards Service for DemoBank"
    version: "3.0.0"
    termsOfService: "http://demobank.com/terms"
    contact:
      name: "Dragos Lech"
      email: "dragos@demobank.com"

logging:
  level:
    org.sumeet: DEBUG
    org.springframework.cloud.gateway: INFO